# Generated by Django 6.0.5 on 2026-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_feedbackinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackinquiry',
            name='imo_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackinquiry',
            name='mmsi_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedbackinquiry',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
