# Generated by Django 6.0.5 on 2026-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortCallCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_unlocode", models.CharField(db_index=True, max_length=20)),
                (
                    "search_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "vessel_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "port call caches",
            },
        ),
        migrations.AddConstraint(
            model_name="portcallcache",
            constraint=models.UniqueConstraint(
                fields=("port_unlocode", "search_type", "vessel_type"),
                name="unique_port_call_cache",
            ),
        ),
    ]
