# Generated by Django 6.0.5 on 2026-05-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VesselInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mmsi', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('ship_type', models.CharField(blank=True, max_length=100)),
                ('callsign', models.CharField(blank=True, max_length=20)),
                ('teu', models.CharField(blank=True, max_length=50)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('beam', models.CharField(blank=True, max_length=50)),
                ('draught', models.CharField(blank=True, max_length=50)),
                ('eni', models.CharField(blank=True, max_length=50)),
                ('eta_utc', models.CharField(blank=True, max_length=100)),
                ('deadweight', models.CharField(blank=True, max_length=50)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('atd_utc', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(blank=True, max_length=20)),
                ('heading', models.CharField(blank=True, max_length=20)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('hull', models.CharField(blank=True, max_length=100)),
                ('builder', models.CharField(blank=True, max_length=255)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('place_of_build', models.CharField(blank=True, max_length=255)),
                ('position_received', models.CharField(blank=True, max_length=100)),
                ('ballast_water', models.CharField(blank=True, max_length=100)),
                ('crude_oil', models.CharField(blank=True, max_length=50)),
                ('fresh_water', models.CharField(blank=True, max_length=50)),
                ('gas', models.CharField(blank=True, max_length=50)),
                ('grain', models.CharField(blank=True, max_length=50)),
                ('bale', models.CharField(blank=True, max_length=50)),
                ('unlocode_destination', models.CharField(blank=True, max_length=20)),
                ('unlocode_lastport', models.CharField(blank=True, max_length=20)),
                ('last_port', models.CharField(blank=True, max_length=255)),
                ('country_iso', models.CharField(blank=True, max_length=10)),
                ('type_specific', models.CharField(blank=True, max_length=100)),
                ('navigational_status', models.CharField(blank=True, max_length=100)),
                ('gross_tonnage', models.CharField(blank=True, max_length=50)),
                ('net_tonnage', models.CharField(blank=True, max_length=50)),
                ('year_of_built', models.CharField(blank=True, max_length=10)),
                ('engine', models.JSONField(blank=True, default=dict)),
                ('management', models.JSONField(blank=True, default=dict)),
                ('update_time', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'vessel info',
            },
        ),
        migrations.CreateModel(
            name='VesselLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('eta_utc', models.CharField(blank=True, max_length=100)),
                ('atd_utc', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=20)),
                ('heading', models.CharField(blank=True, max_length=20)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('draught', models.CharField(blank=True, max_length=50)),
                ('navigational_status', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('last_port', models.CharField(blank=True, max_length=255)),
                ('callsign', models.CharField(blank=True, max_length=20)),
                ('position_received', models.CharField(blank=True, max_length=100)),
                ('update_time', models.CharField(blank=True, max_length=100)),
                ('unlocode_destination', models.CharField(blank=True, max_length=20)),
                ('unlocode_lastport', models.CharField(blank=True, max_length=20)),
                ('type_specific', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='vessels.vesselinfo')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VesselWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('wind_speed', models.CharField(blank=True, max_length=50)),
                ('waves', models.CharField(blank=True, max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='vessels.vesselinfo')),
            ],
            options={
                'verbose_name_plural': 'vessel weather',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
